# Generated by Django 5.0.1 on 2024-01-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.ManyToManyField(related_name='products', to='shop.tag', verbose_name='Теги'),
        ),
    ]
